[package]
name = "ngone-cli"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
clap = { version = "3.0.10", features = ["derive"] }
shadow-rs = "0.8"

[build-dependencies]
shadow-rs = "0.8"
